name: Build Multi-Platform Installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            output: exe
          - os: macos-latest
            output: dmg
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze
        pip install -r requirements.txt
    
    - name: Build with cx_Freeze
      run: python setup.py build
    
    - name: Create Windows MSI
      if: matrix.os == 'windows-latest'
      run: python setup.py bdist_msi
    
    - name: Create macOS DMG
      if: matrix.os == 'macos-latest'
      run: python setup.py bdist_dmg
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: installer-${{ matrix.os }}
        path: |
          dist/*.msi
          dist/*.dmg
